# This is meant for local development only! Do not use this in production.
version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - docker.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hoonnotes
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - docker.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - hoonnotes
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  hoonnotes:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
