FROM node:22-alpine AS development

WORKDIR /app

RUN apk add --no-cache libc6-compat


COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm install --frozen-lockfile --prefer-offline; \
  else echo "Lockfile not found." && exit 1; \
  fi


# COPY application code
COPY . .

# Set environment variables
ENV NODE_ENV=Development
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--turbopack"]